//POST_FROM数据来源
export enum POST_FROM {
    CURRENT_USER_PUBLISHED_POSTS,
    CURRENT_USER_FAVORITES_POSTS,
    LATEST_POSTS,
    MAIN_POSTS,
    OTHER_USER_PUBLISHED_POSTS,
    OTHER_USER_FAVORITES_POSTS,
    UNKNOWN
}
